-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@120",
    position = "0x0",
    scale    = "1.6",
})

-- 100Hz, not 60Hz: 1920x1080@60 is a CTA-861 TV mode, which makes NVIDIA drive
-- the link as limited-range RGB (16-235). The Samsung then expands it, crushing
-- everything above 235 to flat white (faint UI borders disappear). 100Hz is a
-- PC-only timing, so the link negotiates full range. Bonus: 100Hz.
hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x1080@100",
    position = "2560x0",
    scale    = "1",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "fuzzel"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
hl.on("hyprland.start", function ()
    -- Lock immediately on startup (acts as the login/greeter screen)
    hl.exec_cmd("hyprlock")

    hl.exec_cmd("waybar")
    hl.exec_cmd('swaybg -i "$(cat ~/.cache/wallpaper 2>/dev/null || echo /home/ossama/Pictures/Wallpapers/leaves-2560.png)" -m fill')

    -- Idle daemon (screen dim / lock / dpms / suspend)
    hl.exec_cmd("hypridle")

    -- Tray applets removed: waybar's own network/bluetooth modules already show
    -- these, so the applets only added duplicate tray icons on the right.
    -- (If you ever need GUI wifi-password / bluetooth-pairing prompts, re-enable
    --  the relevant line, or use nmtui / blueman-manager instead.)
    -- hl.exec_cmd("nm-applet --indicator")
    -- hl.exec_cmd("blueman-applet")

    -- Clipboard history: watch text + images and store them via cliphist
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 5,

        border_size = 2,

        col = {
            -- Active: sage gradient. Inactive: dark/recessed.
            active_border   = { colors = {"rgba(505f4cee)", "rgba(7a836dee)"}, angle = 45 },
            inactive_border = "rgba(3c3836aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 4,
            passes    = 3,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Curves, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
-- "Smooth slides" preset: calm ease-out curves, no overshoot/bounce.
hl.curve("glide",        { type = "bezier", points = { {0.215, 0.61}, {0.355, 1} } }) -- easeOutCubic: gentle landing
hl.curve("smooth",       { type = "bezier", points = { {0.25, 1},     {0.5, 1}   } }) -- easeOutQuint-ish: long soft tail
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5},    {0.75, 1}  } })
hl.curve("linear",       { type = "bezier", points = { {0, 0},        {1, 1}     } })

-- speed = duration in 1/10 s (higher = slower). Tuned for a fluid, gliding feel.
hl.animation({ leaf = "global",        enabled = true,  speed = 7,    bezier = "smooth" })
hl.animation({ leaf = "border",        enabled = true,  speed = 8,    bezier = "smooth" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 2.5,  bezier = "glide",        style = "popin 0%" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 2.5,  bezier = "glide",        style = "popin 0%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 2.5,  bezier = "glide",        style = "popin 0%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 5,    bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 5,    bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 5,    bezier = "almostLinear" })
-- Snappy launcher/layer pop-in: short durations + a light scale (popin) that
-- reads faster than a slide. (speed = duration in 1/10 s; lower = faster.)
hl.animation({ leaf = "layers",        enabled = true,  speed = 3,    bezier = "glide" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 2,    bezier = "glide",        style = "popin 90%" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "glide",        style = "popin 90%" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 2,    bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.5,  bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4,    bezier = "smooth",       style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 4,    bezier = "smooth",       style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 4,    bezier = "smooth",       style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "smooth" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})
-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

hl.config({
  cursor = {
    -- Must stay true on this machine: hardware cursors force aquamarine to blit
    -- the cursor buffer between the Intel iGPU and the NVIDIA dGPU driving
    -- HDMI-A-2. That blit fails (glCheckFramebufferStatus 1282) and leaks the
    -- EGLImage it just created -- ~17 KB per cursor update, ~20 MB/min of
    -- active mouse use. Cost 5 GB of RAM over a 21h session on Hyprland 0.56.0.
    no_hardware_cursors = true,
  },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


-------------------
---- XWAYLAND ----
-------------------

-- See https://wiki.hypr.land/Configuring/Variables/#xwayland
-- Without this, XWayland apps are handed a 1600x1000 screen (2560x1600 / 1.6)
-- and Hyprland upscales their output by the monitor scale -> blurry. DaVinci
-- Resolve is XWayland-only, so it takes the full brunt of that.
-- Zero scaling hands XWayland the real 2560x1600 and renders it 1:1 instead.
-- Apps that don't scale themselves then draw small; Resolve has its own
-- Preferences > User > UI Settings > UI Display Scale to compensate.
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
-- Toggle floating; when the window BECOMES floating, size it to 960x600 (≈60%
-- of the 1600x1000 usable area) and center it. Toggling back to tiled is left
-- untouched. NOTE: this build (Hyprland 0.55, Lua config) routes `hyprctl
-- dispatch` through the Lua engine, so we pass hl.dsp.* expressions, not the
-- classic string dispatchers (togglefloating/resizeactive/centerwindow).
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(
    [[hyprctl dispatch 'hl.dsp.window.float({ action = "toggle" })'; ]] ..
    [[hyprctl activewindow | grep -q 'floating: 1' && { ]] ..
    [[hyprctl dispatch 'hl.dsp.window.resize({ exact = true, x = 960, y = 600 })'; ]] ..
    [[hyprctl dispatch 'hl.dsp.window.center()'; }]]))
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + t", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + h",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j",  hl.dsp.focus({ direction = "down" }))

-- Move / swap the active window within the tree with mainMod + SHIFT + hjkl
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",        hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + ALT + S",  hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Lock the screen (also triggered automatically by hypridle / on suspend)
-- Moved off SUPER+SHIFT+L to avoid clashing with the move-window-right bind.
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))

-- Screenshots (grim + slurp). Saved to ~/Pictures/Screenshots and copied to clipboard.
-- SUPER + SHIFT + S -> select a region, save to file + copy to clipboard
-- SUPER + SHIFT + F -> whole screen,   save to file + copy to clipboard
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim -g \"$(slurp)\" \"$f\" && wl-copy < \"$f\""))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim \"$f\" && wl-copy < \"$f\""))

-- Color picker (hyprpicker): copies hex to clipboard
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Clipboard history picker (cliphist via fuzzel's dmenu mode)
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"))

-- Audio mixer GUI
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("pavucontrol"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Fuzzel launcher: dim + blur the background for a focused, modern popup.
hl.layer_rule({
    name       = "fuzzel-dim-blur",
    match      = { namespace = "^fuzzel$" },
    dim_around = true,
    blur       = true,
})

-- Waybar: layer-shell surfaces (bars, launchers) are NOT covered by
-- decoration.blur.enabled the way normal windows are -- each one needs its
-- own layer_rule opt-in, or its translucent background just stays flat.
-- Only fuzzel had one; waybar's rgba(40,40,40,0.85) bar was falling through.
hl.layer_rule({
    name  = "waybar-blur",
    match = { namespace = "^waybar$" },
    blur  = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Kdenlive file dialogs (Add Clip, etc.) open far too small on Hyprland,
-- crushing the file-list pane to nothing. Force a usable, centered size.
hl.window_rule({
    name   = "kdenlive-file-dialog",
    match  = { class = "^org.kde.kdenlive$", title = "^Kdenlive$", float = true },

    float  = true,
    size   = "1200 800",
    center = true,
})
